### ISSUE TITLE
Question: could this have worked more like the 0.1 -> 0.2 tokio-compat crate?

### ISSUE THREAD

**Issue by krallin** [LucioFranco/tokio-compat-02#13]
In the 0.1 -> 0.2 compat crate (i.e. tokio-compat), it was possible to update the runtime instantiation instead of updating all the callsites.  That model made it possible to follow this path to update:

- Update your runtimes to tokio-compat (this is pretty easy)
- Gradually update callsites & dependencies to Tokio 0.2
- Update the runtime to tokio 0.2

We were hoping to be able to do the same with the 0.2 to 1.0 update, but that seems impossible since instead we would need to identify all the callsites in one go and wrap them with `.compat()` calls. 

This is a little tricky since (in contrast to runtime instantiation which is usually in `main()`), those callsites might be hidden pretty deep in dependencies (so finding where to add `.compat()` isn't necessarily trivial). We'd also need to make sure we remove those `.compat()` calls as those dependencies get updated.

I totally understand that this might be out of scope for this crate, but I'd like to explore whether we should support this ourselves. 

So, considering this had been done differently in the previous update,  I'm curious to know whether you've given this approach any thought, and if you have: are you aware of specific blockers that would make what was done in the 0.1 -> 0.2 update impossible in the 0.2 -> 1.0 update? 

Thanks!

**Comment by Darksonn** [comment]
The short answer is that doing this would require adding quite a few hooks into the 0.2 runtime so one could replace both the spawner, timer and IO drivers, and this is not exactly trivial to do.

That said, I think that unless your dependencies are spawning with `tokio_02::spawn`, it shouldn't be that bad. You can wrap an entire task in `.compat()` at the spawn-site, which makes 0.2 usable in the entirety of that task.

**Comment by krallin** [comment]
> The short answer is that doing this would require adding quite a few hooks into the 0.2 runtime so one could replace both the spawner, timer and IO drivers, and this is not exactly trivial to do.

Thanks, that's what I feared :)

> That said, I think that unless your dependencies are spawning with tokio_02::spawn, it shouldn't be that bad. You can wrap an entire task in .compat() at the spawn-site, which makes 0.2 usable in the entirety of that task.

We do have some spawning like this. But more broadly speaking, our dependencies are shared across our entire codebase and used by dozens of teams, so identifying the tasks that need wrapping in `compat()` is a little tricky when things are constantly changing (and judging from past experience attempting the 0.1 -> 0.2 update before tokio-compat crate existed).

--

Anyhow, thanks for the quick response, that's what I needed to know! :)
